### ISSUE TITLE
请问下，怎么定义nmap的参数

### ISSUE THREAD

**Issue by awei84** [yhy0/RustScan#2]
例如 rustscan --scan-order random  -a xx.xx.xx.xx  -- -Pn -sV

-- -Pn -sV从哪里输入啊

**Comment by yhy0** [comment]
我没写，你可以研究代码看下怎么写，当时就是为了扫描器写的，后来还是弃用了 rustscan + nmap ,还是回归masscan+nmap
,这个项目没啥用了，抱歉

**Comment by awei84** [comment]
> 我没写，你可以研究代码看下面怎么写，当时就是为了扫描器写的，后来还是弃用了 russcan + nmap ，还是回归 masscan+nmap ，这个项目没有啥用了，抱 慢

好的，谢谢大佬，请问为什么弃用russcan+nmap啊，我刚准备从masscan+nmap 转过来，尴尬

**Comment by yhy0** [comment]
当时效果好像不是很好，你也可以试试，如果效果好的话，教教我。
这个你要自定义 nmap 参数也好写，参考一下这些函数的写法，也很简单，比如这个
https://github.com/yhy0/RustScan/blob/master/rustscan.go#L311

**Comment by awei84** [comment]
👌🏻好的，我自己改改试试，感谢
